env:
  global:
    - CODECOV_TOKEN="f69126fc-452f-4b09-be0b-ac415d95ebaa"

language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту 71m25@mail.ru если сборка упала
notifications:
  email:
    recipients:
      -71m25@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
